---
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/bundle/**/*'
    - 'test/dummy/**/*'
    - 'test/test_helper.rb'

#Lint/UnderscorePrefixedVariableName:
#  Exclude:
#    - 'lib/active_record/embedded/model.rb'
#    - 'test/test_helper.rb'
#
#Metrics/BlockLength:
#  CountComments: false
#  ExcludedMethods:
#    - class_methods
#    - refine
#  Max: 36
#
#Naming/MethodParameterName:
#  Exclude:
#    - 'lib/active_record/embedded/model/storage.rb'
#
#Style/DoubleNegation:
#  Exclude:
#    - 'lib/active_record/embedded/field/boolean.rb'
